// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO9SYKat06pNsV_docBFdfgGc1l_9VBnY',
    appId: '1:79768156871:web:9edbcf1e4497e10dab1ce2',
    messagingSenderId: '79768156871',
    projectId: 'horizonx-2f779',
    authDomain: 'horizonx-2f779.firebaseapp.com',
    storageBucket: 'horizonx-2f779.appspot.com',
    measurementId: 'G-Q5CDW7NB2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6skJXahSrfm_g6o-jAO3BgZJLnKcC3VU',
    appId: '1:79768156871:android:bdd6da8da12dc160ab1ce2',
    messagingSenderId: '79768156871',
    projectId: 'horizonx-2f779',
    storageBucket: 'horizonx-2f779.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt0ccOpyDtSdX6QMlcfqC2SRHsREpwkUk',
    appId: '1:79768156871:ios:9f684962758c3995ab1ce2',
    messagingSenderId: '79768156871',
    projectId: 'horizonx-2f779',
    storageBucket: 'horizonx-2f779.appspot.com',
    iosBundleId: 'com.example.horizonx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt0ccOpyDtSdX6QMlcfqC2SRHsREpwkUk',
    appId: '1:79768156871:ios:9f684962758c3995ab1ce2',
    messagingSenderId: '79768156871',
    projectId: 'horizonx-2f779',
    storageBucket: 'horizonx-2f779.appspot.com',
    iosBundleId: 'com.example.horizonx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO9SYKat06pNsV_docBFdfgGc1l_9VBnY',
    appId: '1:79768156871:web:0a34ebe08350e5afab1ce2',
    messagingSenderId: '79768156871',
    projectId: 'horizonx-2f779',
    authDomain: 'horizonx-2f779.firebaseapp.com',
    storageBucket: 'horizonx-2f779.appspot.com',
    measurementId: 'G-S86N7C7FM4',
  );
}
